version: '3.3'

services:
  java:
    build: java
    ports:
      - "8080:8080"
    container_name: unity-java
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://unity-database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - CUSTOM_HTTP_MAX_FILE_SIZE=9000MB
      - CUSTOM_HTTP_MAX_REQUEST_SIZE=9050MB
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - .\videos:/app/src/main/resources/videos

  angular:
    build: angular
    ports:
      - "4200:80"
    container_name: unity-angular
    volumes:
      - .\videos:/app/src/assets/videos

  db:
    image: 'postgres:latest'
    container_name: unity-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - .\database:/var/lib/postgresql/data